### ISSUE TITLE
TypeError: Cannot read property 'constructor' of undefined

### ISSUE THREAD

**Issue by zygimantus** [BonsaiDen/Maple.js#11]
`node demo/server.js` gives this error:

```
/home/test/Projects/NodeJS/maple.js/lib/Class.js:72
            clas[key] = (value[c] == func)
                              ^

TypeError: Cannot read property 'constructor' of undefined
    at BaseClass (/home/test/Projects/NodeJS/maple.js/lib/Class.js:72:31)
    at Object.<anonymous> (/home/test/Projects/NodeJS/maple.js/lib/WebSocket.js:31:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/test/Projects/NodeJS/maple.js/Server.js:27:23)
```

What are the solutions to this problem?

**Comment by daPhantom** [comment]
Probably since the lib wasn't updated in 5 years.
